name: Update Tire Inventory

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at noon UTC
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Run inventory update
      run: node .github/workflows/update-inventory.js
    - name: Commit and push if changed
      run: |
        git config --local user.email "automation@sturgeontire.com"
        git config --local user.name "Tire Bot"
        if [[ -n $(git status --porcelain) ]]; then
          git add index.html
          git commit -m "🤖 Auto-update tire inventory $(date +%Y-%m-%d)"
          git push
        fi
