name: Update Tire Inventory

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at noon UTC
  workflow_dispatch: # Manual trigger
  push:
    branches: ["main"]
  # Trigger on any push to main, then check if CSV changed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check if CSV changed
      id: csv-check
      run: |
        # Check if CSV file was modified in the last commit
        if git diff HEAD~1 --name-only | grep -q "flyer_data.csv"; then
          echo "CSV file changed, proceeding with update"
          echo "csv_changed=true" >> $GITHUB_OUTPUT
        else
          echo "CSV file not changed, skipping unless manual trigger"
          echo "csv_changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Debug - List files
      if: steps.csv-check.outputs.csv_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
      run: |
        echo "Current directory:"
        ls -la
        echo "CSV file check:"
        ls -la *.csv || echo "No CSV files found"
        echo "CSV file content preview:"
        head -5 flyer_data.csv || echo "Cannot read CSV"
        
    - name: Run inventory update
      if: steps.csv-check.outputs.csv_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
      run: node .github/workflows/update-inventory.js
      
    - name: Check for changes
      if: steps.csv-check.outputs.csv_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
      id: git-check
      run: |
        git diff --exit-code index.html || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push updated index.html
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.name "Tire Bot"
        git config --local user.email "bot@sturgeon-tire.com"
        git add index.html
        git commit -m "🤖 Auto-update tire inventory $(date +'%Y-%m-%d %H:%M')"
        git push
